params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  open_door_1216_3:
    path_to_network_params: /home/htung/Documents/2020/Fall/pdc/trained_models/tutorials/open_door_images512_1220_3/090000.pth

dataset: [] # which dataset to use, not used for now

output_dir: analysis
